Creare clasa Page
alexalbu98/Crawler pull request #16
Opened 2020-12-03 21:32 UTC by teocalugaru

Issue: #11
Implementeaza scheletul clasei Page, utilizata
pentru a retine URL-ul unei pagini.

Signed-off-by: Teo Calugaru <calugaruteodor@yahoo.com>

2020-12-04 13:06 UTC, NotRealPeople approved these changes

2020-12-04 17:56 UTC, alexalbu98 approved these changes
Totul pare ok.

2020-12-04 22:08 UTC, irasdesire approved these changes

2020-12-05 06:19 UTC, NotRealPeople submitted a review, later dismissed

2020-12-05 09:57 UTC, alexalbu98 requested changes
Trebuie modificata denumirea packegului com in mta si adaugarea claseleor in foldere ca mai jos:

/src
      /mta
             /main/Main.java
             /Classes/Crawler.java
             /Classes/Page.java

2020-12-05 13:35 UTC, alexalbu98 submitted a review, later dismissed
Totul pare ok.

2020-12-05 13:35 UTC, NotRealPeople approved these changes

2020-12-05 13:37 UTC, irasdesire submitted a review, later dismissed

2020-12-05 13:48 UTC, alexalbu98 submitted a review, later dismissed

2020-12-05 13:50 UTC, alexalbu98 approved these changes

2020-12-05 13:51 UTC, NotRealPeople approved these changes
nice job m8

2020-12-05 13:52 UTC, irasdesire approved these changes

2020-12-05 13:53 UTC, closed without merging