Modificare fisier de configurare
alexalbu98/Crawler pull request #41
Opened 2020-12-11 19:08 UTC by teocalugaru

2020-12-11 19:40 UTC, irasdesire submitted a review, later dismissed

2020-12-12 06:38 UTC, alexalbu98 requested changes
Sunt conflicte, Incearca sa le rezolvi local si dupa mai incarca o data.

2020-12-12 18:30 UTC, NotRealPeople approved these changes

2020-12-12 18:36 UTC, alexalbu98 approved these changes

2020-12-12 18:45 UTC, irasdesire approved these changes

2020-12-12 18:48 UTC, merged