Myupdatess
alexalbu98/Crawler pull request #53
Opened 2020-12-19 22:28 UTC by irasdesire

issue: fixes #32, fixes #47
am rezolvat conflictele si bug-urile

Signed-off-by: Ira Mirea iramadd@gmail.com

2020-12-20 14:29 UTC, alexalbu98 submitted a review, later dismissed

2020-12-20 16:19 UTC, NotRealPeople approved these changes

2020-12-21 18:17 UTC, teocalugaru approved these changes

2020-12-21 18:19 UTC, NotRealPeople approved these changes

2020-12-21 18:31 UTC, NotRealPeople requested changes

2020-12-21 18:31 UTC, NotRealPeople commented on src/mta/Classes/Crawler.java
> +            Pages.set(i, p);
Aici e addType(Page), poti schimba, pls

2020-12-21 19:39 UTC, alexalbu98 approved these changes

2020-12-21 21:14 UTC, NotRealPeople approved these changes

2020-12-22 13:25 UTC, merged